CREATE TABLE users (
  `id` VARCHAR (14) NOT NULL, 
  `name` VARCHAR (255) NOT NULL, 
  `email` VARCHAR (255) NOT NULL, 
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on 
  UPDATE 
    CURRENT_TIMESTAMP, 
    PRIMARY KEY (`id`)
);